### ISSUE TITLE
Example Import not accessible with PID

### ISSUE THREAD

**Issue by j-panzer** [subugoe/olahd_backend#7]
The PID retrieved from a successful example import could not be found in the OLAHD. But instead the PID PartID could be found.

This Issue duplicates the Jira issue [OLAHDS-206](https://pm.sub.uni-goettingen.de/browse/OLAHDS-206), please take a look at it for more information.

**Comment by joschrew** [comment]
ocrd-zips/files with a PID can be found but not with searching it via the PID but with its PartID, as you described. Cannot be fixed, we could think about implementing a functionality for accessing ocrd-zips/files with its PID
